ALTER TABLE Authorize CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Apparatus CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Events CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE EventItems CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE EventType CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Exposures CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE ExposureUser CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Incidents CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Narratives CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Narratives CHANGE COLUMN Narrative Narrative TEXT;
ALTER TABLE Narratives CHANGE COLUMN NarrativeHTML NarrativeHTML TEXT;
ALTER TABLE NHTSAPatients CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE NHTSAPersonnel CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE PayrollTimes CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE PayrollItems CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Schedule CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Stations CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
ALTER TABLE Status CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);
##ALTER TABLE Users CHANGE COLUMN IncidentSearchQuery IncidentSearchQuery TEXT;
ALTER TABLE Users CHANGE COLUMN LastUpdate LastUpdate VARCHAR(8);

# INDICES

ALTER TABLE Apparatus ADD INDEX (IDOfApparatusOrResource(10));
ALTER TABLE Apparatus ADD INDEX (EID);
ALTER TABLE Exposures ADD INDEX (ExposureID);
ALTER TABLE Exposures ADD INDEX (IID);
ALTER TABLE Exposures ADD INDEX (UID);
ALTER TABLE ExposureUser ADD INDEX (ExposureId);
ALTER TABLE Incidents ADD INDEX (IncidentID);
ALTER TABLE Incidents ADD INDEX (IncidentDateTime);
ALTER TABLE Narratives ADD INDEX (EID);
ALTER TABLE PayrollItems ADD INDEX (AID);
ALTER TABLE PayrollItems ADD INDEX (ClassID);
#ALTER TABLE PayrollItems ADD INDEX (StationID);
ALTER TABLE Schedule ADD INDEX (AID);
ALTER TABLE Schedule ADD INDEX (ClassID);
ALTER TABLE Stations ADD INDEX (StationID);
ALTER TABLE Users ADD INDEX (UserID);

